apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: userinfo-backend
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: userinfo-backend
  template:
    metadata:
      labels:
        app: userinfo-backend
    spec:
      containers:
        - name: userinfo-backend
          image: 811288377093.dkr.ecr.us-west-2.amazonaws.com/new-userinfo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATE
              value: 'DATE_STRING'
          env:   # Setting Enviornmental Variables
            - name: HOST_NAME   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : db-secrets
                  key :  username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : db-secrets
                  key :  password
  strategy:
    blueGreen:
      activeService: userinfo-backend
      previewService: userinfo-backend-preview
      autoPromotionEnabled: false




---
apiVersion: v1
kind: Service
metadata:
  name: userinfo-backend
spec:
  selector:
    app:  userinfo-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: userinfo-backend-preview
spec:
  selector:
    app:  userinfo-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort : 30084
      protocol: TCP