---
apiVersion: v1
kind: Service
metadata:
  name: userinfo-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/userinfoes"
spec:
  selector:
    app:  userinfo-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
